# Change this and ../WORKSPACE at the same time
FROM quay.io/calico/envoy:20171130-d75df7a
ADD pilot-agent /usr/local/bin/pilot-agent

COPY envoy_pilot.json      /etc/istio/proxy/envoy_pilot.json
COPY envoy_pilot_auth.json /etc/istio/proxy/envoy_pilot_auth.json
COPY envoy_mixer.json      /etc/istio/proxy/envoy_mixer.json
COPY envoy_mixer_auth.json /etc/istio/proxy/envoy_mixer_auth.json

ENTRYPOINT ["/usr/local/bin/pilot-agent"]
